---
title: "Aggregate biomass"
format:
  html:
    code-fold: true
---

```{r setup}
knitr::opts_chunk$set(
  fig.height = 4,
  warning = FALSE,
  message = FALSE
)
```

```{r}
survdat <- "\\\\nefscdata\\EDAB_Datasets\\Workflows\\surveyNoLengthsData.rds" |>
  readRDS()

# species_key <- "\\\\nefscdata\\EDAB_Datasets\\Workflows\\SOE_species_list_24.rds" |>
#   readRDS()

species_key <- here::here("data/SVSPP_species_list.csv") |>
  read.csv()

data <- survdat$survdat
EPU <- c('MAB', 'GB', 'GOM', 'SS')
MAB <- c(1010:1080, 1100:1120, 1600:1750, 3010:3450, 3470, 3500, 3510)
GB <- c(1090, 1130:1210, 1230, 1250, 3460, 3480, 3490, 3520:3550)
GOM <- c(1220, 1240, 1260:1290, 1360:1400, 3560:3830)
SS <- c(1300:1352, 3840:3990)
```

## Bulk aggregate biomass by EPU

```{r, results = "hide"}
for(i in c("MAB", "GB", "GOM")){
  dat <- survdat::calc_stratified_mean(
    data |>
      dplyr::mutate(group = "unit"),
    filterByArea = get(i),
    filterBySeason = c('FALL', 'SPRING'),
    groupDescription = 'group',
    tidy = TRUE
  ) 
  
  n_strat <- data |> dplyr::filter(STRATUM %in% get(i))
  
  n_0_strata <- length(get(i)) - length(unique(n_strat$STRATUM))
  
  plt <- dat |>
    dplyr::filter(variable == "strat.biomass") |>
    ggplot2::ggplot(ggplot2::aes(x = YEAR, 
                                 y = value,
                                 color = SEASON)) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::theme_bw() +
    ggplot2::ggtitle(paste(i, "stratified mean biomass")) +
    ggplot2::labs(caption = paste("number of strata with no observations:", n_0_strata))
  
  print(plt)
}
```

## Managed vs unmanaged species

```{r, results = "hide"}

joined_dat <- data |>
  dplyr::left_join(species_key, 
                   by = c("SVSPP" = "SVSPP")) |>
  dplyr::mutate(Fed.Managed = dplyr::case_when(is.na(Fed.Managed) ~ "Unmanaged",
                                               Fed.Managed == "ASMFC " ~ "ASMFC", 
                                               TRUE ~ Fed.Managed))

for(i in c("MAB", "GB", "GOM")){
  dat <- survdat::calc_stratified_mean(
    joined_dat,
    filterByArea = get(i),
    filterBySeason = c('FALL', 'SPRING'),
    groupDescription = 'Fed.Managed',
    tidy = TRUE
  ) 
  
  # n_strat <- data |> dplyr::filter(STRATUM %in% get(i))
  # 
  # n_0_strata <- length(get(i)) - length(unique(n_strat$STRATUM))
  
  plt <- dat |>
    dplyr::filter(variable == "strat.biomass") |>
    dplyr::group_by(Fed.Managed) |>
    dplyr::mutate(n = dplyr::n()) |>
    dplyr::filter(n > 4) |>
    dplyr::ungroup() |>
    ggplot2::ggplot(ggplot2::aes(x = YEAR, 
                                 y = value,
                                 color = SEASON)) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::theme_bw() +
    ggplot2::facet_wrap(~Fed.Managed,
                        scales = "free_y") +
    ggplot2::ggtitle(paste(i, "stratified mean biomass")) #+
    # ggplot2::labs(caption = paste("number of strata with no observations:", n_0_strata))
  
  print(plt)
}
```


```{r, results = "hide"}
#| fig-height: 12

for(i in c("MAB", "GB", "GOM")){
  dat <- survdat::calc_stratified_mean(
    joined_dat |>
      dplyr::mutate(Fed.Managed = ifelse(stringr::str_detect(Fed.Managed, ", Protected Species"), stringr::str_remove(Fed.Managed, ", Protected Species"), Fed.Managed),
                    cat = paste0(Fed.Managed, "_", SVSPP)),
    filterByArea = get(i),
    filterBySeason = c('FALL', 'SPRING'),
    groupDescription = 'cat',
    tidy = TRUE
  ) 
 
  for(j in c("NEFMC", "MAFMC", "ASMFC", "JOINT")) {
    cat(i, j, "stratified mean biomass")
  
  plt <- dat |>
    dplyr::filter(stringr::str_detect(cat, j)) |>
    dplyr::mutate(SVSPP = stringr::str_remove(cat, paste0(j, "_")) |>
                    as.numeric()) |>
    dplyr::left_join(species_key) |>
    dplyr::filter(variable == "strat.biomass",
                  !is.na(COMNAME)) |>
    ggplot2::ggplot(ggplot2::aes(x = YEAR, 
                                 y = value,
                                 fill = COMNAME)) +
    ggplot2::geom_col() +
    ggplot2::theme_bw() +
    ggplot2::facet_grid(cols = ggplot2::vars(SEASON),
                        rows = ggplot2::vars(SOE.24),
                        scales = "free_y") +
    ggplot2::ggtitle(paste(i, j, "stratified mean biomass")) +
    ggplot2::theme(legend.position = "bottom")
    # ggplot2::labs(caption = paste("number of strata with no observations:", n_0_strata))
  
  print(plt)
  }
}
```


## Species-level changes

Looking at species seen in 10+ years, with an average > 1 kg/tow.

```{r, results = "hide", eval = FALSE}
species_dat <- data |>
  dplyr::group_by(YEAR, SEASON, SVSPP) |>
  dplyr::mutate(n = dplyr::n()) |>
  dplyr::filter(n > 2)|>
  dplyr::select(-n) |>
  dplyr::ungroup()

joined_names <- species_dat |>
  dplyr::left_join(species_key, 
                   by = c("SVSPP" = "SVSPP")) 

svspps <- unique(joined_names$SVSPP) |> sort()

 # library(data.table)

message("starting loop")

for(i in c("MAB", "GB", "GOM")){
      dat <- survdat::calc_stratified_mean(
    data,
    filterByArea = get(i),
    filterBySeason = c('FALL', 'SPRING'),
    groupDescription = 'SVSPP',
    tidy = TRUE
  ) 
      cat(i, "stratified mean biomass")
    cat("Aggregate abundance trend of consistently-observed species")

    n_0_strata <- length(get(i)) - length(unique(data$STRATA))
    
    
        plt <- dat |>
          dplyr::filter(variable == "strat.biomass") |>
          # dplyr::mutate(SVSPP = as.factor(SVSPP)) |>
    ggplot2::ggplot(ggplot2::aes(x = YEAR,
                                 y = value,
                                 fill = SVSPP)) +
    ggplot2::geom_col() +
    ggplot2::theme_bw() +
    ggplot2::labs(title = paste(i, "stratified mean biomass -- consistent species only")) +
      viridis::scale_fill_viridis() +
      ggplot2::theme(legend.position = "bottom") +
          ggplot2::facet_wrap(~SEASON)

  print(plt)
  
  cat("Species abundances")
      
      for(j in unique(dat$SVSPP)) {
        ## TODO: figure out if strata with 0 observations are skewing results
        
        this_dat <- dat |>
          dplyr::filter(SVSPP == j,
                        variable == "strat.biomass")
        
        if(nrow(this_dat) > 10 &
           mean(this_dat$value) > 1) {
          name <- paste(joined_names$COMNAME[joined_names$SVSPP == j][1],
                  joined_names$SCINAME[joined_names$SVSPP == j][1])
      
    plt <- this_dat |>
    ggplot2::ggplot(ggplot2::aes(x = YEAR,
                                 y = value,
                                 color = SEASON)) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::theme_bw() +
    ggplot2::labs(title = paste(i, j, "stratified mean biomass"),
                     subtitle = name)

  print(plt)
        }
      }
  }


```

