

# {{ species }}

## Socioeconomic indicators

```{r socioeco-data}
url <- "https://raw.githubusercontent.com/NEFSC/READ-EDAB-NEesp2/refs/heads/2026_esp/data/intermediate/{{ species }}_Commercial_Indicators_Master.csv"
data <- read.csv(url)
```

Get the data used to make the socioeconomic indicator plots [here](`r url`).

### Average price per pound

```{r}
avgprice <- data |>
  dplyr::filter(INDICATOR_NAME == "AVGPRICE_{{ species }}_2025_DOLlb") 

NEesp2::plt_indicator(data = avgprice,
                      ar = 1/4,
                      include_trends = TRUE) 
```

### Total commercial landings (pounds)

```{r}
landings <- data |>
  dplyr::filter(INDICATOR_NAME == "Commercial_{{ species }}_Landings_LBS") 

NEesp2::plt_indicator(data = landings,
                      ar = 1/4,
                      include_trends = TRUE)
```

### Total commercial revenue

```{r}
totalrev <- data |>
  dplyr::filter(INDICATOR_NAME == "TOTALANNUALREV_{{ species }}_2025Dols") 

NEesp2::plt_indicator(data = totalrev,
                      ar = 1/4,
                      include_trends = TRUE)
```

### Number of commercial vessels

```{r}
nvessels <- data |>
  dplyr::filter(INDICATOR_NAME == "N_Commercial_Vessels_Landing_{{ species }}") 

NEesp2::plt_indicator(data = nvessels,
                      ar = 1/4,
                      include_trends = TRUE)
```

### Average revenue per vessel ($USD2024)

```{r}
vesselrev <- data |>
  dplyr::filter(INDICATOR_NAME == "AVGVESREVperYr_{{ species }}_2025_DOLlb") 

NEesp2::plt_indicator(data = vesselrev,
                      ar = 1/4,
                      include_trends = TRUE)
```

## Ecosystem indicators

### Monthly bottom temperature in stock area

```{r bt-data}
url1 <- "https://raw.githubusercontent.com/NEFSC/READ-EDAB-NEesp2/refs/heads/dev_AT/data-raw/2026/{{ species }}_hubert_bottomT.csv"
url2 <- "https://raw.githubusercontent.com/NEFSC/READ-EDAB-NEesp2/refs/heads/dev_AT/data-raw/2026/{{ species }}_glorys_bottomT.csv"
```

```{r}
check_url_exists <- function(url) {
  tryCatch({
    # Create a request and perform a HEAD pulse
    resp <- httr2::request(url) |>
      httr2::req_method("HEAD") |> 
      httr2::req_perform()
    
    # Status code 200 means it exists and is accessible
    return(httr2::resp_status(resp) == 200)
    
  }, error = function(e) {
    # If the URL is broken or the server is down, return FALSE
    return(FALSE)
  })
}
```

```{r, eval = check_url_exists(url1) & check_url_exists(url2), results = "asis"}
cat("Get the data used to make the bottom temperature indicator plots [here (pre-2021)](", url1, ") and [here (2021 and later)](", url2, ").", sep = "")
```

```{r, eval = check_url_exists(url1) & check_url_exists(url2)}
bt_data <- read.csv(url1) |>
  dplyr::bind_rows(read.csv(url2)) |>
  dplyr::group_by(AREA, MONTH, YEAR, INDICATOR_NAME, INDICATOR_UNITS) |>
  dplyr::summarise(DATA_VALUE = mean(DATA_VALUE, na.rm = TRUE), .groups = "drop") |>
  dplyr::mutate(INDICATOR_NAME = "monthly_bottomT")

for(i in 1:12) {
  print(
    bt_data |>
      dplyr::filter(MONTH == i) |>
      NEesp2::plt_indicator(
        ar = 1/4,
        include_trends = TRUE
      ) +
      ggplot2::ggtitle(paste0("Monthly bottom temperature in stock area - ", month.abb[i]))
  )
}
```

```{r, eval = !(check_url_exists(url1) & check_url_exists(url2))}
cat("Bottom temperature for this species hasn't been calculated yet.")
```