---
title: "NEFSC bottom trawl survey strata"
format: pdf
execute: 
  warning: FALSE
---

```{r}
#| eval: TRUE
#| echo: FALSE

knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      fig.width = 12#,
                      # out.width = "100%"
                      )

# load R packages
library(tidyverse) 
library(sf)

# Load strata without printing anything to the screen
strata <- st_read(dsn = here::here("data-raw/stratamap", "strata.shp"))
```

```{r}
plt_strata_subset <- function(data, strata) {
  
  this_data <- data |>
    dplyr::filter(STRATA != 0,
                  STRATA != 99999,
                  STRATA %in% strata)
  
  ggplot() +
    geom_sf(data = rnaturalearth::ne_countries(scale = 10,
                       continent = "North America",
                       returnclass = "sf")) +
  geom_sf(data = this_data, 
          ggplot2::aes(fill = STRATA), 
          colour = "darkgray") + # All strata
  ggrepel::geom_label_repel(data = this_data, 
                            aes(label = STRATA, # 4 digit strata = "STRATA", 5 digit strata = "STRATUMA"
                                               geometry = geometry), 
                            stat = "sf_coordinates", 
                            size = 2,
                            box.padding = 0.1,
                            label.padding = 0.1,
                            force = 0.5,
                            max.overlaps = 20) + # Label with offset, try adjusting max.overlaps if you want to see more labels
  #geom_sf_label(data = filter(strata, STR2 != 0), aes(label = STR2), size = 1) + # Label directly
    viridis::scale_fill_viridis() +
  xlab("Longitude") + ylab("Latitude") +
  coord_sf(xlim = c(-79,-65), ylim = c(32, 45)) # try adjusting axes to see more labels for smaller portion of footprint
  
  ggplot2::ggsave(filename = here::here("data-raw/stratamap", paste0("strata_", min(strata), "_", max(strata), ".png")),
         width = 8,
         height = 12,
         units = "in",
         dpi = 300)
}
```
## All strata

```{r}
plt_strata_subset(data = strata,
                  strata = 1000:9000)
```

## 1000s strata

```{r}
plt_strata_subset(data = strata,
                  strata = 1000:1999)
```

```{r, results = "asis"}
for(i in c(1:3,6,7)) {
res <- knitr::knit_child(text = knitr::knit_expand(text = "```{r}
                                                   plt_strata_subset(data = strata,
                                                   strata = 1{{i}}00:1{{i}}99)
                                                   ```"),
                         quiet = TRUE)
cat(paste0("### 1", i, "00s strata"), res, sep = "\n\n")
}
```

## 3000s strata

```{r}
plt_strata_subset(data = strata,
                  strata = 3000:3999)
```

## 7000s strata

```{r}
plt_strata_subset(data = strata,
                  strata = 7000:7999)
```
